In [2]:
import numpy as np
import pandas as pd
import MF 
import importlib
importlib.reload(MF)




<module 'MF' from 'C:\\Users\\jaehun\\Desktop\\recommender_system\\MF.py'>

In [3]:
GT = pd.read_csv('기태.csv')
HY = pd.read_csv('혜연.csv')
EH = pd.read_excel('은하.xlsx')
SB = pd.read_csv('수빈.csv')
JH = pd.read_csv('정현.csv')

print(GT.head())
print(HY.head())
print(EH.head())
print(SB.head())
print(JH.head())

   user_id  place_id  평점
0     2522         4   5
1     2522         5   2
2     2522         6   5
3     2522         8   5
4     2522        10   4
   user_id  place_id  평점
0     2524         3   4
1     2524        16   4
2     2524        20   5
3     2524        22   3
4     2524        23   4
   user_id         이름  평점
0     2519      언니네반점   3
1     2519       고른햇살   3
2     2519     돈까스하우스   1
3     2519  서울쌈냉면 고대점   5
4     2519        용초수   4
       맛집  평점  user_id  place_id
0    고른햇살   4     2523         9
1   미스터국밥   4     2523        13
2   이세돈까스   3     2523        22
3  매스플레이트   4     2523        49
4    치폴레옹   5     2523       110
          이름  평점  user_id
0       우승식당   5     2520
1  히포크라테스 스프   3     2520
2     고대맛집ㅋㅋ   2     2520
3       고른햇살   5     2520
4        고품콩   4     2520


In [4]:
place_data = pd.read_csv('merged_place_data.csv')

In [5]:
df = pd.read_csv('ratings.csv')
r_df = df[['user_id', 'place_id', '평점']]
print(r_df)

      user_id  place_id   평점
0           1         1  5.0
1           2         1  5.0
2           3         1  3.0
3           4         1  4.0
4           5         1  4.0
...       ...       ...  ...
6897     2253       407  5.0
6898     2254       407  5.0
6899     2409       408  5.0
6900     2497       409  5.0
6901     2499       410  5.0

[6902 rows x 3 columns]


In [6]:
my_data = [[2521, 41, 4.0], [2521, 11, 4.0], [2521, 13, 4.0], [2521, 3, 2.0], 
        [2521, 12, 5.0], [2521, 29, 3.0], [2521, 55, 2.0], [2521, 119, 3.0], [2521, 24, 1.0],
          [2521, 79, 2.0], [2521, 290, 2.0], [2521, 405, 3.0], [2521, 270, 3.0], [2521, 384, 5.0],
          [2521, 18, 3.0], [2521, 140, 4.0], [2521, 236, 3.0], [2521, 67, 1.0], [2521, 272, 4.0],
          [2521, 62, 4.0], [2521, 229, 5.0], [2521, 196, 5.0], [2521, 4, 3.0], [2521, 32, 4.0]]
my_df = pd.DataFrame(my_data, columns=r_df.columns)
print(my_df)

    user_id  place_id   평점
0      2521        41  4.0
1      2521        11  4.0
2      2521        13  4.0
3      2521         3  2.0
4      2521        12  5.0
5      2521        29  3.0
6      2521        55  2.0
7      2521       119  3.0
8      2521        24  1.0
9      2521        79  2.0
10     2521       290  2.0
11     2521       405  3.0
12     2521       270  3.0
13     2521       384  5.0
14     2521        18  3.0
15     2521       140  4.0
16     2521       236  3.0
17     2521        67  1.0
18     2521       272  4.0
19     2521        62  4.0
20     2521       229  5.0
21     2521       196  5.0
22     2521         4  3.0
23     2521        32  4.0


In [7]:
temp1 = r_df.append(GT)
print(len(temp1))
print(len(temp1[temp1['user_id']==2522]))
print(len(GT))

6925
23
23


In [8]:
temp2 = temp1.append(HY)
print(len(temp2))
print(len(temp2[temp2['user_id']==2524]))
print(len(HY))

6945
20
20


In [9]:
sb = SB[['user_id', 'place_id', '평점']]
print(sb)

    user_id  place_id  평점
0      2523         9   4
1      2523        13   4
2      2523        22   3
3      2523        49   4
4      2523       110   5
5      2523       208   4
6      2523       105   4
7      2523        25   4
8      2523        24   2
9      2523       184   3
10     2523        23   5
11     2523       187   3
12     2523       230   3
13     2523       107   3
14     2523        59   2
15     2523        80   2
16     2523        53   4
17     2523       130   3
18     2523       188   5
19     2523        16   4
20     2523        18   3
21     2523        19   4


In [10]:
temp3 = temp2.append(sb)
print(len(temp3))
print(len(temp3[temp3['user_id']==2523]))
print(len(sb))

6967
22
22


In [11]:
eh = pd.merge(EH, place_data)
print(len(EH))
print(len(eh))

20
20


In [12]:
print(JH)

           이름  평점  user_id
0        우승식당   5     2520
1   히포크라테스 스프   3     2520
2      고대맛집ㅋㅋ   2     2520
3        고른햇살   5     2520
4         고품콩   4     2520
..        ...  ..      ...
75      춘천닭갈비   3     2520
76    사보텐 고대점   3     2520
77  다돈 참숯화로구이   5     2520
78  서울쌈냉면 고대점   4     2520
79        용초수   5     2520

[80 rows x 3 columns]


In [13]:
jh = pd.merge(JH, place_data)
print(len(JH))
print(len(jh))
jh2 = jh.drop_duplicates(['place_id'], keep='first')
print(len(jh2))

80
78
77


In [14]:
eh2 = eh[['user_id', 'place_id', '평점']]
jh3 = jh2[['user_id', 'place_id', '평점']]

In [15]:
temp4 = temp3.append(eh2)
temp5 = temp4.append(jh3)
ratings_df = temp5.append(my_df)
print(len(ratings_df))

# undupl = ratings_df.groupby(['user_id', 'place_id'], as_index = False).mean()

# print(undupl)
# print(len(undupl['user_id'].unique()))

7088


In [16]:
ratings = ratings_df.pivot(
        index = 'user_id',
        columns = 'place_id',
        values = '평점'
    ).fillna(0)
print(ratings)

place_id  1.0    2.0    3.0    4.0    5.0    6.0    7.0    8.0    9.0    \
user_id                                                                   
1           5.0    2.0    4.0    4.0    4.0    5.0    0.0    0.0    0.0   
2           5.0    0.0    0.0    0.0    0.0    0.0    3.0    5.0    5.0   
3           3.0    4.0    0.0    0.0    0.0    0.0    0.0    0.0    3.0   
4           4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    4.0   
5           4.0    5.0    0.0    4.0    0.0    0.0    0.0    5.0    4.0   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
2520        0.0    0.0    0.0    5.0    0.0    0.0    0.0    2.0    5.0   
2521        0.0    0.0    2.0    3.0    0.0    0.0    0.0    0.0    0.0   
2522        0.0    0.0    0.0    5.0    2.0    5.0    0.0    5.0    0.0   
2523        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    4.0   
2524        0.0    0.0    4.0    0.0    0.0    0.0    0.0    0.0    0.0   

place_id  10.0   ...  40

In [17]:
matrix = ratings.values
print(matrix)


[[5. 2. 4. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]
 [3. 4. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 4. ... 0. 0. 0.]]


In [18]:
mf_model = MF.MatrixFactorization(matrix, k=10, learning_rate=0.05, reg_param=0.01, epochs=100)
mf_model.fit()
pred_matrix = mf_model.reconstruct()


In [19]:
print(pred_matrix)
print(pred_matrix.shape)

[[ 4.89105712  2.02226298  3.92721437 ... -1.07662442  6.86388012
   3.79394492]
 [ 4.76692092  4.37243701  3.67836603 ...  3.69448088  3.61219702
   4.34831926]
 [ 2.98435973  3.9377702   3.9184347  ...  6.29553691  0.87262907
   5.29544211]
 ...
 [ 5.0271846   2.05834876  2.59561109 ...  2.56654773  7.14626142
   2.82115572]
 [ 5.25018064  3.17554692  1.96905527 ...  1.63180108  7.69859739
   3.66491119]
 [ 3.99909499  4.31069377  3.78528879 ...  5.23481125  4.51488962
   3.52333762]]
(2524, 410)


In [20]:
rating_data = pd.merge(ratings_df, place_data)[['이름', 'place_id', '태그', 'user_id', '평점']]
rating_data['place_id'] = rating_data['place_id'].astype(int)
print(rating_data)

                이름  place_id                                       태그  \
0             쭈불쭈불         1  #먹어야산다#한식#불고기#닭갈비#쭈꾸미#정대후문#혼밥#회식#저렴#가성비   
1             쭈불쭈불         1  #먹어야산다#한식#불고기#닭갈비#쭈꾸미#정대후문#혼밥#회식#저렴#가성비   
2             쭈불쭈불         1  #먹어야산다#한식#불고기#닭갈비#쭈꾸미#정대후문#혼밥#회식#저렴#가성비   
3             쭈불쭈불         1  #먹어야산다#한식#불고기#닭갈비#쭈꾸미#정대후문#혼밥#회식#저렴#가성비   
4             쭈불쭈불         1  #먹어야산다#한식#불고기#닭갈비#쭈꾸미#정대후문#혼밥#회식#저렴#가성비   
...            ...       ...                                      ...   
7083           제기집       407                   #먹어야산다#고대사거리#제기동#닭발#회식   
7084           제기집       407                   #먹어야산다#고대사거리#제기동#닭발#회식   
7085          테리키친       408                   #먹어야산다#파스타#리조또#피자#성신여대   
7086           홍릉각       409                    #먹어야산다#중화요리#유니짜장#제기시장   
7087  황박사 통마늘오리주물럭       410                  #먹어야산다#제기동#오리고기#통마늘#몸보신   

      user_id   평점  
0           1  5.0  
1           2  5.0  
2           3  3.0  
3           4  4.0  
4           5  4.0

In [21]:
target_user = rating_data[rating_data['user_id'] == 2519]

In [22]:
print(target_user)

                      이름  place_id  \
150                언니네반점         3   
975                 고른햇살         9   
1151              돈까스하우스        11   
1532           서울쌈냉면 고대점        16   
1980                 용초수        20   
2100          청년다방 고대안암점        23   
2160          치즈를 사랑한 찜닭        25   
2282               고래돈까스        29   
2366                모이리타        31   
2815                금룡짬뽕        42   
2835            나정순할매쭈꾸미        44   
3140  밀플랜비 (Meal Plan B)        55   
3179              본샤브칼국수        57   
3864                 찌개집        79   
3889           철남 (정대후문)        80   
3987                프로마치        83   
4576                다손김밥       123   
4895                 아미가       136   
5342                  미뇽       167   
5505               칠기마라탕       175   

                                              태그  user_id   평점  
150           #먹어야산다#중식#정대후문#사천식#혼밥#가성비#저렴#포장#회식     2519  3.0  
975                     #먹어야산다#분식#정대후문#포장#혼밥#가성비     2519  3.0  
1151  

In [23]:
def predict_rating(user_id, place_id):
    return pred_matrix[user_id - 1][place_id - 1]

In [24]:
target_user['예상평점'] = target_user.apply(lambda x : predict_rating(2519, x['place_id']), axis=1)
target_user.sort_values(by='평점', ascending=False)

c:\users\jaehun\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


이름  place_id  \
5505               칠기마라탕       175   
1532           서울쌈냉면 고대점        16   
4895                 아미가       136   
2160          치즈를 사랑한 찜닭        25   
2366                모이리타        31   
3987                프로마치        83   
3889           철남 (정대후문)        80   
3864                 찌개집        79   
5342                  미뇽       167   
1980                 용초수        20   
4576                다손김밥       123   
2815                금룡짬뽕        42   
150                언니네반점         3   
3179              본샤브칼국수        57   
3140  밀플랜비 (Meal Plan B)        55   
975                 고른햇살         9   
2100          청년다방 고대안암점        23   
2835            나정순할매쭈꾸미        44   
2282               고래돈까스        29   
1151              돈까스하우스        11   

                                              태그  user_id   평점      예상평점  
5505           #먹어야산다#중식#마라탕#마라샹궈#정문앞#꿔바로우#포장#혼밥     2519  5.0  5.029259  
1532              #먹어야산다#한식#냉면#정대후문#포장#혼밥#저렴#가성비     2519  5.0  4.985772  
4895                     #먹어야산다#한식#백반#법대후문#포장#혼밥     2519  5.0  4.995985  
2160                        #먹어야산다#한식#찜닭#정대후문#포장     2519  5.0  4.959824  
2366       #먹어야산다#양식#파스타#리조또#피자#참살이길#데이트#회식#모이리따     2519  5.0  5.046308  
3987  #먹어야산다#양식#다이어트#샌드위치#샐러드#수프#참살이길#옆살이길#혼밥#포장     2519  5.0  4.956165  
3889                 #먹어야산다#한식#두루치기#정대후문#회식#철판남매     2519  5.0  5.001062  
3864              #먹어야산다#한식#백반#김치찌개#참살이길#뒷살이길#회식     2519  4.0  3.997893  
5342                        #먹어야산다#양식#제기동#브런치#감성     2519  4.0  4.002363  
1980              #먹어야산다#중식#사천식#꿔바로우#정대후문#포장#가성비     2519  4.0  4.029352  
4576                  #먹어야산다#분식#김밥#수제비#정문앞#포장#혼밥     2519  4.0  3.997371  
2815        #먹어야산다#중식#중화요리#짜장면#짬뽕#탕수육#참살이길#포장#혼밥     2519  4.0  4.014901  
150           #먹어야산다#중식#정대후문#사천식#혼밥#가성비#저렴#포장#회식     2519  3.0  3.141734  
3179            #먹어야산다#참살이길#한식#버섯칼국수#샤브샤브#혼밥#가성비     2519  3.0  3.043778  
3140            #먹어야산다#정대후문#멕시칸#부리또#핫도그#혼밥#저렴#포장     2519  3.0  3.090662  
975                     #먹어야산다#분식#정대후문#포장#혼밥#가성비     2519  3.0  3.194537  
2100         #먹어야산다#참살이길#끝쪽#안암로터리#분식#퓨전#떡볶이#감자튀김     2519  3.0  3.009049  
2835                        #먹어야산다#쭈꾸미#이공계#안암로터리     2519  2.0  2.036964  
2282              #먹어야산다#일식#돈까스#정문앞#포장#혼밥#회식#가성비     2519  1.0  1.004242  
1151            #먹어야산다#경양식#돈까스#정대후문#포장#혼밥#가성비#돈하     2519  1.0  1.208941

In [25]:
recommendations = rating_data[rating_data['place_id'].isin(target_user['place_id']) == False][['이름', 'place_id', '태그']].drop_duplicates()
recommendations['예상평점'] = recommendations.apply(lambda x: predict_rating(2519, x['place_id']), axis=1)
recommendations.sort_values(by='예상평점', ascending=False).head(20)


이름  place_id                                 태그  \
6168               고대사랑 엄나무       233      #먹어야산다#한식#곰탕#설렁탕#백반#정문앞#혼밥#저렴   
5067                   철든돼지       152           #먹어야산다#법후#배달#삼겹살#불고기#도시락   
7082                종암골 생고기       406  #먹어야산다#고기#소주#한식#백반#정문앞#고려대역#포장#회식   
7085                   테리키친       408             #먹어야산다#파스타#리조또#피자#성신여대   
2210            한솥도시락 고대안암점        27           #먹어야산다#도시락#정대후문#배달#포장#혼밥   
7016                  거북이식당       361       #먹어야산다#한식#기사식당#백반집#제기동#고대사거리   
267   ¸¾½ºÅÍÄ¡ ŸÀÌ°ÅÇöóÀÚ         7  #¸Ô¾î¾ß»ê´Ù#Çܹö°Å#±³³»#Æ÷Àå#È¥¹ä   
7011                    포몬스       359       #먹어야산다#동남아#쌀국수#참살이길#배달#포장#혼밥   
6985                     예손       349              #먹어야산다#한식#백반#혼밥#화정체육관   
5250               산학관 학생식당       161                             #먹어야산다   
6412                  마마돈가스       257      #먹어야산다#법대후문#고려대역#일식#분식#돈까스#혼밥   
6897                  종구네통닭       325                     #먹어야산다#치킨#청량리역   
6164                      .       232                #먹어야산다#신마라탕페이지로가주세요   
6530             신포1971 안암점       271      #먹어야산다#한식#퓨전#쫄면#만두#참살이길#포장#혼밥   
4181              두끼떡볶이 고대점        96                  #먹어야산다#분식#참살이길#포장   
7049                     하루       386          #먹어야산다#종암동#스시#초밥#사시미#이자까야   
6594                    옥당골       277  #먹어야산다#한식#백반#오리#백숙#삼계탕#법대후문#포장#혼밥   
7036                  로라방앗간       375                 #먹어야산다#떡볶이#납작만두#튀김   
6787                   샐러데이       300         #먹어야산다#다이어트#샐러드#정대후문#테이크아웃   
6993          통큰두마리찜닭 성신여대점       352               #먹어야산다#찜닭#배달#한식#성신여대   

           예상평점  
6168  11.840355  
5067  11.492637  
7082  10.159859  
7085   9.263930  
2210   9.019125  
7016   8.880273  
267    8.152152  
7011   8.043826  
6985   7.828417  
5250   7.784651  
6412   7.694719  
6897   7.645773  
6164   7.645468  
6530   7.327250  
4181   7.320807  
7049   7.201654  
6594   7.131700  
7036   6.950818  
6787   6.915154  
6993   6.877507