In [157]:
import numpy as np
import pandas as pd
import MF 
import importlib
importlib.reload(MF)




<module 'MF' from 'C:\\Users\\jaehun\\Desktop\\recommender_system\\MF.py'>

Data Preprocessing & Merging  
실제 게시판 data + 팀원들의 평가 data 

In [ ]:
GT = pd.read_csv('기태.csv')
HY = pd.read_csv('혜연.csv')
EH = pd.read_excel('은하.xlsx')
SB = pd.read_csv('수빈.csv')
JH = pd.read_csv('정현.csv')

print(GT.head())
print(HY.head())
print(EH.head())
print(SB.head())
print(JH.head())

In [159]:
place_data = pd.read_csv('merged_place_data.csv')

In [160]:
df = pd.read_csv('ratings.csv')
r_df = df[['user_id', 'place_id', '평점']]
print(r_df)

      user_id  place_id   평점
0           1         1  5.0
1           2         1  5.0
2           3         1  3.0
3           4         1  4.0
4           5         1  4.0
...       ...       ...  ...
6897     2253       407  5.0
6898     2254       407  5.0
6899     2409       408  5.0
6900     2497       409  5.0
6901     2499       410  5.0

[6902 rows x 3 columns]


In [161]:
my_data = [[2521, 41, 4.0], [2521, 11, 4.0], [2521, 13, 4.0], [2521, 3, 2.0], 
        [2521, 12, 5.0], [2521, 29, 3.0], [2521, 55, 2.0], [2521, 119, 3.0], [2521, 24, 1.0],
          [2521, 79, 2.0], [2521, 290, 2.0], [2521, 405, 3.0], [2521, 270, 3.0], [2521, 384, 5.0],
          [2521, 18, 3.0], [2521, 140, 4.0], [2521, 236, 3.0], [2521, 67, 1.0], [2521, 272, 4.0],
          [2521, 62, 4.0], [2521, 229, 5.0], [2521, 196, 5.0], [2521, 4, 3.0], [2521, 32, 4.0]]
my_df = pd.DataFrame(my_data, columns=r_df.columns)
print(my_df)

    user_id  place_id   평점
0      2521        41  4.0
1      2521        11  4.0
2      2521        13  4.0
3      2521         3  2.0
4      2521        12  5.0
5      2521        29  3.0
6      2521        55  2.0
7      2521       119  3.0
8      2521        24  1.0
9      2521        79  2.0
10     2521       290  2.0
11     2521       405  3.0
12     2521       270  3.0
13     2521       384  5.0
14     2521        18  3.0
15     2521       140  4.0
16     2521       236  3.0
17     2521        67  1.0
18     2521       272  4.0
19     2521        62  4.0
20     2521       229  5.0
21     2521       196  5.0
22     2521         4  3.0
23     2521        32  4.0


In [162]:
temp1 = r_df.append(GT)
print(len(temp1))
print(len(temp1[temp1['user_id']==2522]))
print(len(GT))

6925
23
23


In [163]:
temp2 = temp1.append(HY)
print(len(temp2))
print(len(temp2[temp2['user_id']==2524]))
print(len(HY))

6945
20
20


In [164]:
sb = SB[['user_id', 'place_id', '평점']]
print(sb)

    user_id  place_id  평점
0      2523         9   4
1      2523        13   4
2      2523        22   3
3      2523        49   4
4      2523       110   5
5      2523       208   4
6      2523       105   4
7      2523        25   4
8      2523        24   2
9      2523       184   3
10     2523        23   5
11     2523       187   3
12     2523       230   3
13     2523       107   3
14     2523        59   2
15     2523        80   2
16     2523        53   4
17     2523       130   3
18     2523       188   5
19     2523        16   4
20     2523        18   3
21     2523        19   4


In [165]:
temp3 = temp2.append(sb)
print(len(temp3))
print(len(temp3[temp3['user_id']==2523]))
print(len(sb))

6967
22
22


In [166]:
eh = pd.merge(EH, place_data)
print(len(EH))
print(len(eh))

20
20


In [167]:
print(JH)

           이름  평점  user_id
0        우승식당   5     2520
1   히포크라테스 스프   3     2520
2      고대맛집ㅋㅋ   2     2520
3        고른햇살   5     2520
4         고품콩   4     2520
..        ...  ..      ...
75      춘천닭갈비   3     2520
76    사보텐 고대점   3     2520
77  다돈 참숯화로구이   5     2520
78  서울쌈냉면 고대점   4     2520
79        용초수   5     2520

[80 rows x 3 columns]


In [168]:
jh = pd.merge(JH, place_data)
print(len(JH))
print(len(jh))
jh2 = jh.drop_duplicates(['place_id'], keep='first')
print(len(jh2))

80
78
77


In [169]:
eh2 = eh[['user_id', 'place_id', '평점']]
jh3 = jh2[['user_id', 'place_id', '평점']]

In [170]:
temp4 = temp3.append(eh2)
temp5 = temp4.append(jh3)
ratings_df = temp5.append(my_df)
print(len(ratings_df))

7088


In [171]:
ratings = ratings_df.pivot(
        index = 'user_id',
        columns = 'place_id',
        values = '평점'
    ).fillna(0)
print(ratings)

place_id  1.0    2.0    3.0    4.0    5.0    6.0    7.0    8.0    9.0    \
user_id                                                                   
1           5.0    2.0    4.0    4.0    4.0    5.0    0.0    0.0    0.0   
2           5.0    0.0    0.0    0.0    0.0    0.0    3.0    5.0    5.0   
3           3.0    4.0    0.0    0.0    0.0    0.0    0.0    0.0    3.0   
4           4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    4.0   
5           4.0    5.0    0.0    4.0    0.0    0.0    0.0    5.0    4.0   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
2520        0.0    0.0    0.0    5.0    0.0    0.0    0.0    2.0    5.0   
2521        0.0    0.0    2.0    3.0    0.0    0.0    0.0    0.0    0.0   
2522        0.0    0.0    0.0    5.0    2.0    5.0    0.0    5.0    0.0   
2523        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    4.0   
2524        0.0    0.0    4.0    0.0    0.0    0.0    0.0    0.0    0.0   

place_id  10.0   ...  40

In [172]:
# 전체 data set (matrix)
matrix = ratings.values
print(matrix)

[[5. 2. 4. ... 0. 0. 0.]
 [5. 0. 0. ... 0. 0. 0.]
 [3. 4. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 4. ... 0. 0. 0.]]


MF 모델은 전체 data set인 matrix를 train data set / validation data set 으로 split한 후, train data만을 가지고 학습 진행  

주요 hyperparameter : k (학습할 latent factor 수), learning_rate, reg_param(정규화 파라미터 값), epochs  

tolerance : Early Stopping 수행을 위한 매개변수  




In [173]:
mf_model = MF.MatrixFactorization(matrix, k=10, learning_rate=0.05, reg_param=0.01, epochs=100, val_prop=0.2, tolerance=5)


In [174]:
print(len(mf_model._val_user_indices))

206968


val_prop 만큼 matrix nonzero => zero(학습에 사용되지 않는다)  
validation date set 확보  

In [175]:
print(np.count_nonzero(mf_model._train_R))
print(np.count_nonzero(mf_model._R))


5811
7088


In [176]:
train_logs = mf_model.fit()
pred_matrix = mf_model.reconstruct()

In [177]:
print(pred_matrix)
print(train_logs)

[[5.03059774 2.01877135 3.97263608 ... 2.27314046 2.44144788 4.14485942]
 [4.96645255 2.52355864 3.53820399 ... 3.60048653 2.9071948  4.20580164]
 [3.02427174 2.66967852 2.98449186 ... 2.5485425  3.30936854 2.96283477]
 ...
 [5.12285934 2.02816764 2.69348089 ... 5.4622985  3.66638282 5.24266   ]
 [2.68247263 4.14601367 4.12772855 ... 2.51563193 3.68736322 2.61851384]
 [5.73954354 1.42866477 3.93215478 ... 3.33840532 1.85101624 4.38243914]]
[[0, 0.8681015381801127, 2.9872831534922537], [5, 0.27457292499165536, 2.580423039706487], [10, 0.19020772098498734, 2.6094422904083183], [15, 0.1459063822234326, 2.622031869260125], [20, 0.1175785911018106, 2.6251636979863435], [25, 0.09766668053343561, 2.624948885139328], [30, 0.08311361817290533, 2.6221486456560705], [35, 0.07213424159812211, 2.6167404273940336], [40, 0.06357203093335108, 2.6089712325676726], [45, 0.05671806085848204, 2.599392317498457], [50, 0.051126208518559126, 2.588611983181504], [55, 0.04648407149577655, 2.577058468426451], [

In [178]:
print(train_logs[-1])

[95, 0.026603122937684024, 2.4657658221025813]


95 epoch, 10 latent factors =>  
train MSE : 0.026  
validation MSE : 2.465  

In [ ]:
############# 적용 ##############

특정 User에 대한 개인화 추천 적용  

In [179]:
rating_data = pd.merge(ratings_df, place_data)[['이름', 'place_id', '태그', 'user_id', '평점']]
rating_data['place_id'] = rating_data['place_id'].astype(int)
print(rating_data)

                이름  place_id                                       태그  \
0             쭈불쭈불         1  #먹어야산다#한식#불고기#닭갈비#쭈꾸미#정대후문#혼밥#회식#저렴#가성비   
1             쭈불쭈불         1  #먹어야산다#한식#불고기#닭갈비#쭈꾸미#정대후문#혼밥#회식#저렴#가성비   
2             쭈불쭈불         1  #먹어야산다#한식#불고기#닭갈비#쭈꾸미#정대후문#혼밥#회식#저렴#가성비   
3             쭈불쭈불         1  #먹어야산다#한식#불고기#닭갈비#쭈꾸미#정대후문#혼밥#회식#저렴#가성비   
4             쭈불쭈불         1  #먹어야산다#한식#불고기#닭갈비#쭈꾸미#정대후문#혼밥#회식#저렴#가성비   
...            ...       ...                                      ...   
7083           제기집       407                   #먹어야산다#고대사거리#제기동#닭발#회식   
7084           제기집       407                   #먹어야산다#고대사거리#제기동#닭발#회식   
7085          테리키친       408                   #먹어야산다#파스타#리조또#피자#성신여대   
7086           홍릉각       409                    #먹어야산다#중화요리#유니짜장#제기시장   
7087  황박사 통마늘오리주물럭       410                  #먹어야산다#제기동#오리고기#통마늘#몸보신   

      user_id   평점  
0           1  5.0  
1           2  5.0  
2           3  3.0  
3           4  4.0  
4           5  4.0

In [180]:
target_user = rating_data[rating_data['user_id'] == 2519]

In [181]:
print(target_user)

                      이름  place_id  \
150                언니네반점         3   
975                 고른햇살         9   
1151              돈까스하우스        11   
1532           서울쌈냉면 고대점        16   
1980                 용초수        20   
2100          청년다방 고대안암점        23   
2160          치즈를 사랑한 찜닭        25   
2282               고래돈까스        29   
2366                모이리타        31   
2815                금룡짬뽕        42   
2835            나정순할매쭈꾸미        44   
3140  밀플랜비 (Meal Plan B)        55   
3179              본샤브칼국수        57   
3864                 찌개집        79   
3889           철남 (정대후문)        80   
3987                프로마치        83   
4576                다손김밥       123   
4895                 아미가       136   
5342                  미뇽       167   
5505               칠기마라탕       175   

                                              태그  user_id   평점  
150           #먹어야산다#중식#정대후문#사천식#혼밥#가성비#저렴#포장#회식     2519  3.0  
975                     #먹어야산다#분식#정대후문#포장#혼밥#가성비     2519  3.0  
1151  

In [182]:
def predict_rating(user_id, place_id):
    return pred_matrix[user_id - 1][place_id - 1]

In [183]:
target_user['예상평점'] = target_user.apply(lambda x : predict_rating(2519, x['place_id']), axis=1)
target_user.sort_values(by='평점', ascending=False)

c:\users\jaehun\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


이름  place_id  \
5505               칠기마라탕       175   
1532           서울쌈냉면 고대점        16   
4895                 아미가       136   
2160          치즈를 사랑한 찜닭        25   
2366                모이리타        31   
3987                프로마치        83   
3889           철남 (정대후문)        80   
3864                 찌개집        79   
5342                  미뇽       167   
1980                 용초수        20   
4576                다손김밥       123   
2815                금룡짬뽕        42   
150                언니네반점         3   
3179              본샤브칼국수        57   
3140  밀플랜비 (Meal Plan B)        55   
975                 고른햇살         9   
2100          청년다방 고대안암점        23   
2835            나정순할매쭈꾸미        44   
2282               고래돈까스        29   
1151              돈까스하우스        11   

                                              태그  user_id   평점      예상평점  
5505           #먹어야산다#중식#마라탕#마라샹궈#정문앞#꿔바로우#포장#혼밥     2519  5.0  0.141636  
1532              #먹어야산다#한식#냉면#정대후문#포장#혼밥#저렴#가성비     2519  5.0  5.052666  
4895                     #먹어야산다#한식#백반#법대후문#포장#혼밥     2519  5.0  4.996216  
2160                        #먹어야산다#한식#찜닭#정대후문#포장     2519  5.0  5.056361  
2366       #먹어야산다#양식#파스타#리조또#피자#참살이길#데이트#회식#모이리따     2519  5.0  2.610403  
3987  #먹어야산다#양식#다이어트#샌드위치#샐러드#수프#참살이길#옆살이길#혼밥#포장     2519  5.0  4.988795  
3889                 #먹어야산다#한식#두루치기#정대후문#회식#철판남매     2519  5.0  4.963701  
3864              #먹어야산다#한식#백반#김치찌개#참살이길#뒷살이길#회식     2519  4.0  5.230892  
5342                        #먹어야산다#양식#제기동#브런치#감성     2519  4.0  4.665070  
1980              #먹어야산다#중식#사천식#꿔바로우#정대후문#포장#가성비     2519  4.0  4.010341  
4576                  #먹어야산다#분식#김밥#수제비#정문앞#포장#혼밥     2519  4.0  3.988131  
2815        #먹어야산다#중식#중화요리#짜장면#짬뽕#탕수육#참살이길#포장#혼밥     2519  4.0  4.008738  
150           #먹어야산다#중식#정대후문#사천식#혼밥#가성비#저렴#포장#회식     2519  3.0  2.998851  
3179            #먹어야산다#참살이길#한식#버섯칼국수#샤브샤브#혼밥#가성비     2519  3.0  3.018622  
3140            #먹어야산다#정대후문#멕시칸#부리또#핫도그#혼밥#저렴#포장     2519  3.0  3.021043  
975                     #먹어야산다#분식#정대후문#포장#혼밥#가성비     2519  3.0  3.137178  
2100         #먹어야산다#참살이길#끝쪽#안암로터리#분식#퓨전#떡볶이#감자튀김     2519  3.0  2.975888  
2835                        #먹어야산다#쭈꾸미#이공계#안암로터리     2519  2.0  2.028060  
2282              #먹어야산다#일식#돈까스#정문앞#포장#혼밥#회식#가성비     2519  1.0  1.069888  
1151            #먹어야산다#경양식#돈까스#정대후문#포장#혼밥#가성비#돈하     2519  1.0  1.057347

In [184]:
recommendations = rating_data[rating_data['place_id'].isin(target_user['place_id']) == False][['이름', 'place_id', '태그']].drop_duplicates()
recommendations['예상평점'] = recommendations.apply(lambda x: predict_rating(2519, x['place_id']), axis=1)
recommendations.sort_values(by='예상평점', ascending=False).head(20)


이름  place_id  \
7073  서초 철판코다리찜 메밀 막국수       401   
7042             나드리김밥       380   
7019          직화갈비 3센치       364   
6304   »ï¼ºÅë´ß ¿À°Å¸®       248   
7082           종암골 생고기       406   
6807             로라방앗간       303   
6921           청진동 해장국       333   
7035                공푸       374   
7083               제기집       407   
2817             꿀삐닭강정        43   
6842          돼야지 고대본점       309   
6028              해마루2       220   
6366         59쌀피자 제기동       252   
6293                콩닭       245   
7007            라이라이라이       355   
6079           피자헛 안암점       225   
6367             서안메밀집       253   
4288      오거리 맥반석 통닭트럭       104   
7018              벤베누토       363   
5896       등촌샤브칼국수 안암점       208   

                                                     태그       예상평점  
7073                            #먹어야산다#이공계#보문#한식#막국수#혼밥  11.245170  
7042                                #먹어야산다#교내#안암병원#고대병원  10.057078  
7019                           #먹어야산다#신설동#고기#갈비#무한리필#직화   9.858154  
6304  #¸Ô¾î¾ß»ê´Ù#ġŲ#Âü»ìÀ̱æ#¹è´Ş#Æ÷Àå#ȸ½Ä#»ïÅëġŲ   9.260678  
7082                  #먹어야산다#고기#소주#한식#백반#정문앞#고려대역#포장#회식   8.894564  
6807                               #먹어야산다#이공계#분식#떡볶이#컵밥   8.669987  
6921                        #먹어야산다#한식#국밥#해장국#법대후문#포장#혼밥   8.554879  
7035                        #먹어야산다#차돌짬뽕#짜장#미니탕수육#성신여대입구   8.505185  
7083                             #먹어야산다#고대사거리#제기동#닭발#회식   8.317244  
2817                                 #먹어야산다#보문#닭강정#안암초교   8.051039  
6842                               #먹어야산다#고기#참살이길#포장#회식   7.891692  
6028                 #먹어야산다#한식#퓨전#돈까스#떡볶이#정문앞#혼밥#저렴#가성비   7.795810  
6366                    #먹어야산다#피자#제기동#고대사거리#포장#배달#오구쌀피자   7.705835  
6293                             #먹어야산다#안암로터리#치킨#닭강정#포장   7.673468  
7007                          #먹어야산다#성신여대입구#동남아#반미#샌드위치   7.568141  
6079                      #먹어야산다#이공계#보문#피자#포장#배달#혼밥#가성비   7.430613  
6367             #먹어야산다#한식#수육#국수#제기동#포장#혼밥#회식#고대사거리#가성비   7.341305  
4288                            #먹어야산다#안암로터리#통닭트럭#오거리통닭   7.327605  
7018                                   #먹어야산다#성신여대#이탈리안   7.270450  
5896                   #먹어야산다#한식#샤브샤브#칼국수#정대후문#포장#혼밥#회식   7.232975